---
## Install eclipse.
#

# good example how to deal with eclipse programmatically:
# https://github.com/AlbanAndrieu/ansible-eclipse/blob/master/tasks/eclipse.yml

- name: ensure that install directory exists
  file:
    path: '{{sts.install_dir}}'
    state: directory
    mode: 0755

- name: install STS
  unarchive:
    src: '{{sts.url}}'
    dest: '{{sts.install_dir}}'
    creates: '{{sts.install_dir}}/sts-bundle'

- name: get installation directory
  find:
    file_type: directory
    paths: '{{ (sts.install_dir + "/sts-bundle") | expanduser }}'
    patterns: sts-*
    recurse: no
  register: sts_install_status

- name: set STS facts
  set_fact:
    sts_path: '{{sts_install_status.files[0].path}}'
    sts_release: '{{sts_install_status.files[0].path | basename}}'
    sts_version: '{{sts_install_status.files[0].path
                  | basename | regex_replace("^sts-(.*)$", "\\1") }}'

- name: tweak STS.ini
  lineinfile:
    dest: '{{sts_path}}/STS.ini'
    regexp: '^{{item.key}}'
    line: '{{item.key}}{{item.value}}'
    state: present
  with_dict:
    '-Xms': 512m
    '-Xmx': 1024m
    '-XX:MaxPermSize=': 1024m

- name: create desktop entry
  ini_file:
    dest: '~/.local/share/applications/{{sts_release}}.desktop'
    section: Desktop Entry
    option: '{{item.key}}'
    value: '{{item.value}}'
  with_dict:
    Type: Application
    Version: 1.0
    Encoding: UTF-8
    Name: 'Spring Tool Suite {{sts_version}}'
    Exec: '{{sts_path}}/STS'
    Icon: '{{sts_path}}/icon.xpm'
    Terminal: false
    Categories: Application;

- name: create workspace
  file:
    path: '{{sts.workspace_dir}}/workspace-{{sts_release}}'
    state: directory
    mode: 0755

- name: copy workspace settings
  copy:
    src: workspace/
    dest: '{{sts.workspace_dir}}/workspace-{{sts_release}}'
    force: yes
