---
## Configure Firefox.
#
# This task:
# * creates profile
# * installs addons
# * sets preferences
#
# You have to manually enable addons
# in Tools -> Add-ons or about:addons
#

- name: create profile
  shell: >
    dirname $(firefox -CreateProfile default 2>&1
    | tail -n 1 | awk -F "'" '{print $(NF-1)}')
  register: ff_profile

- name: register profile directory
  set_fact:
    ff_profile_dir: '{{ff_profile.stdout}}'

- name: ensure that extensions directory exists
  file:
    path: '{{ff_profile_dir}}/extensions'
    state: directory
    mode: 0755

- name: install addons
  firefox_addon:
    src: '{{item.value}}'
    dest: '{{ff_profile_dir}}/extensions'
  with_dict: '{{firefox_addons}}'
  register: ff_addons

- name: move config
  template:
    src: prefs.js.j2
    dest: '{{ff_profile_dir}}/prefs.js'

- name: show menu bar and bookmarks toolbar
  copy:
    content: >
      {"chrome://browser/content/browser.xul":{
        "toolbar-menubar":{"autohide":"false"},
        "PersonalToolbar":{"collapsed":"false"}
      }}
    dest: '{{ff_profile_dir}}/xulstore.json'
