---

deadbeef:
  install_dir: ~/.opt
  library: /media/michal3/d7c4765f-449b-48b1-b1e5-882b8158f5c5/muzyka
  url: "http://sourceforge.net/projects/deadbeef/files/\
        deadbeef-static_0.6.2-2_{{arch.x86_64_or_i686}}.tar.bz2/download"
  plugins:
    filebrowser:
      url: "http://sourceforge.net/projects/deadbeef/\
            files/plugins/{{arch.x86_64_or_i686}}/\
            ddb_filebrowser-98a1458-{{arch.x86_64_or_i686}}.zip/download"
