---
## Set-up bash prompt.
#

- name: ensure .bashrc.d exists
  file:
    path: ~/.bashrc.d
    state: directory
    mode: 0755

- name: fetch git-completion scripts
  get_url:
    url: '{{item.url}}'
    dest: '{{item.dest}}'
    force: yes
  with_items:
    - dest: ~/.bashrc.d/01-git-completion.bash
      url: "https://raw.githubusercontent.com/git/git/\
            master/contrib/completion/git-completion.bash"
    - dest: ~/.bashrc.d/02-git-prompt.sh
      url: "https://raw.githubusercontent.com/git/git/\
            master/contrib/completion/git-prompt.sh"

- name: copy PS1 script
  copy:
    src: git-prompt-ps1.sh
    dest: ~/.bashrc.d/03-git-prompt-ps1.sh
