
alias ls='ls --color=auto'
alias ssh='ssh -XC'
alias ssh-phone='/usr/bin/ssh -p 2222 -c aes128-gcm@openssh.com root@black'

if hash exa 2>/dev/null; then
  alias ll='exa --long --classify --all --group --git --sort=name'
  alias tree='exa --tree --long --classify --all --group --sort=name -I=".git|.svn"'
else
  alias ll='ls -l --classify --almost-all --human-readable --literal --reverse'
  alias tree='tree -a -I ".git|.svn"'
fi

if hash pygmentize 2>/dev/null; then
  alias hl='pygmentize -g'
elif hash highlight 2>/dev/null; then
  alias hl='highlight -O ansi --failsafe'
fi

if hash imv 2>/dev/null; then
  alias imv='imv -d'
fi

alias swayland='\
  GDK_BACKEND=wayland \
  CLUTTER_BACKEND=wayland \
  QT_QPA_PLATFORM=wayland-egl \
  QT_WAYLAND_FORCE_DPI=physical \
  ECORE_EVAS_ENGINE=wayland_egl \
  ELM_ENGINE=wayland_egl \
  SDL_VIDEODRIVER=wayland \
  _JAVA_AWT_WM_NONREPARENTING=1 \
  KITTY_ENABLE_WAYLAND=1 \
  sway'

# For some reason kitty sets TERMINFO to a directory with only xterm-kitty entry.
# If tmux is started within kitty, TERM is changed to tmux-256color.
# unibilium's unibi_from_term(...) fails because tmux's entry is not in TERMINFO.
# This forces neovim to fall-back to autogenerated entry builtin_tmux
# As of 3.1, builtin_tmux does not provide smcup/rmcup. It is fixed in 3.2.
# Arch's kitty package puts xterm-kitty entry also in the default location.
# Workaround is to put other entries in TERMINFO(_DIRS) or remove TERMINFO.
# test: rm -f log; TMUX= nvim -V3log; rg -e smcup -e rmcup -e '&term' log
# https://github.com/kovidgoyal/kitty/issues/291
# https://github.com/neovim/neovim/issues/7798
# https://github.com/neovim/neovim/pull/7981
# https://github.com/neovim/neovim/issues/9071

if [[ "$TERMINFO" = *kitty* ]]; then
  # export TERMINFO_DIRS="/usr/share/terminfo:$TERMINFO"
  unset TERMINFO
fi
