---
## Set gnome preferences.
#
# TODO install weather extension
#

- name: tweak gonme settings
  command: 'gsettings set {{item[0]}} {{item[1]}} "{{item[2]}}"'
  with_items: '{{gnome_settings}}'

- name: enable global dark theme
  ini_file:
    dest: ~/.config/gtk-3.0/settings.ini
    state: present
    section: Settings
    option: gtk-application-prefer-dark-theme
    value: 1

# https://wiki.gnome.org/Apps/Terminal/FAQ
# https://git.gnome.org/browse/gnome-terminal
# /tree/src/org.gnome.Terminal.gschema.xml

- name: find default gnome-terminal profile
  command: >
            gsettings get org.gnome.Terminal.ProfilesList default
            | awk -F\' '{ print $2}'
  register: terminal_default_profile

- name: tweak gnome-terminal settings
  command: "gsettings set org.gnome.Terminal.Legacy.Profile:\
            /org/gnome/terminal/legacy/profiles:\
            /:{{terminal_default_profile}}/ \
            {{item[0]}} '{{item[1]}}'"
  with_items: '{{gnome_terminal_settings}}'
