---
## Install and configure Atom.
#

- name: add repository [Ubuntu]
  apt_repository:
    repo: ppa:webupd8team/atom
    update_cache: yes
  become: yes
  become_method: sudo
  when: ansible_distribution in ['Ubuntu']

- name: add repository [Fedora]
  block:
    - name: install dnf-plugins-core
      dnf:
        name: dnf-plugins-core
        state: present
    - name: enable repository
      command: dnf copr enable helber/atom && dnf update
  become: yes
  become_method: sudo
  when: ansible_distribution in ['Fedora']

# TODO arch support

- name: install atom
  package:
    name: atom
    state: latest
  become: yes
  become_method: sudo

- name: install atom packages
  command: 'apm install {{item}}'
  with_items: '{{atom_packages}}'

- name: copy configuration file
  copy:
    src: config.cson
    dest: ~/.atom/config.cson
    force: yes

- name: copy styles file
  copy:
    src: styles.less
    dest: ~/.atom/styles.less
    force: yes
