---

firefox_addons:
  FTDeepDark:  https://addons.mozilla.org/firefox/downloads/latest/295337/platform:2/addon-295337-latest.xpi
  AdblockPlus: https://addons.mozilla.org/firefox/downloads/latest/1865/addon-1865-latest.xpi
  TabMixPlus:  https://addons.mozilla.org/firefox/downloads/latest/1122/addon-1122-latest.xpi
